spring.application.name=APPOINTMENT
server.port=9200

spring.datasource.url=jdbc:postgresql://localhost:5432/hms_appointment_db
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


# AWS Config
aws.s3.bucket-name=hms-appointment-archive
aws.s3.region=ap-south-1
aws.access-key=
aws.secret-key=

# Archive threshold
archive.older-than-days=30

spring.output.ansi.enabled=ALWAYS
logging.pattern.console=%clr(%d{yyyy-MM-dd HH:mm:ss}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} : %m%n

DOCTOR_NOT_FOUND=Doctor Not Found
PATIENT_NOT_FOUND= Patient Not Found

spring.cloud.openfeign.circuitbreaker.enabled=true