spring.application.name=AI-SERVICE
server.port=9300


eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true

gemini.api.key=AIzaSyD0EOasy6D4Eqj64IhEErUqC7K8_oR2CMY